### ISSUE TITLE
Wrong Factoring digits number in via formatLabel function

### ISSUE THREAD

**Issue by SurfVaporizer** [appsthatmatter/GraphView#251]
I get online market data (doubles) with fixed digits number but on the graph on X scale  i can see each time different number of digits after point.
I changed formatLabel function and pass number of digits by paramters.

if (mnFractionDigits != -1)  numberformatter[i].setMaximumFractionDigits(mnFractionDigits);

i commented this block.
double highestvalue = isValueX ? getMaxX(false) : getMaxY();
            double lowestvalue = isValueX ? getMinX(false) : getMinY();
            if (highestvalue - lowestvalue < 0.1) {
                numberformatter[i].setMaximumFractionDigits(6);
            } else if (highestvalue - lowestvalue < 1) {
                numberformatter[i].setMaximumFractionDigits(4);
            } else if (highestvalue - lowestvalue < 20) {
                numberformatter[i].setMaximumFractionDigits(3);
            } else if (highestvalue - lowestvalue < 100) {
                numberformatter[i].setMaximumFractionDigits(1);
            } else {
                numberformatter[i].setMaximumFractionDigits(0);

btw, i use your library in my project Forex Game
https://play.google.com/store/apps/details?id=forex.game

**Comment by appsthatmatter** [comment]
closed, because too old. If the problem still exists, please reopen a new ticket.
