### ISSUE TITLE
BarChart - Left and right bars are cut off

### ISSUE THREAD

**Issue by rwmorey71** [appsthatmatter/GraphView#303]
I have a chart with 7 data points and the first and last bars on the chart are cut off.

**Comment by arober11** [comment]
Appears there have been quite a few changes between v3.1.3 and 4.0.0, anyway also hit this one. The BarGraph specific logic in v3 of the library that shunted the viewport up and down half an xInterval, so you got a full width bar for the first and last entry on screen appears to have been dropped, same goes for the logic that centered the x-labels to the middle of each bar, in v4 they are now left aligned. Anyway the first is trivial to code around e.g.

        double xInterval=1.0;
        graphView.getViewport().setXAxisBoundsManual(true);
        if (dataSeries instanceof BarGraphSeries ) {
            // Hide xLabels for now as no longer centered in the grid, but left aligned per the other types
            graphView.getGridLabelRenderer().setHorizontalLabelsVisible(false);
            // Shunt the viewport, per v3.1.3 to show the full width of the first and last bars. 
            graphView.getViewport().setMinX(dataSeries.getLowestValueX() - (xInterval/2.0));
            graphView.getViewport().setMaxX(dataSeries.getHighestValueX() + (xInterval/2.0));
        } else {
            graphView.getViewport().setMinX(dataSeries.getLowestValueX() );
            graphView.getViewport().setMaxX(dataSeries.getHighestValueX());
        }

**Comment by jboffard** [comment]
This trick works only if you don't need the horizontal labels, and I really need them. Because of that, I can't use this library so in my opinion, this is an important issue.

**Comment by appsthatmatter** [comment]
closed, because too old. If the problem still exists, please reopen a new ticket.

**Comment by chubecode** [comment]
the issue still exist for me.

**Comment by rwmorey71** [comment]
I have migrated to this library https://github.com/PhilJay/MPAndroidChart

**Comment by tatran5** [comment]
I am still struggling to resolve this

**Comment by chubecode** [comment]
> I am still struggling to resolve this

How it's going?
