### ISSUE TITLE
GraphView with date values not displayed

### ISSUE THREAD

**Issue by TheNetStriker** [appsthatmatter/GraphView#329]
I've just tried to add some Datapoints with date values, but as soon as I switch from simple integer values (1,2,3...) to date values the GraphView does not render anymore. Here is the data I load into GraphView:

 0 = {com.jjoe64.graphview.series.DataPoint@830038856144} "[1.428713480673E12/74.0]"
  x = 1.428713480673E12
  y = 74.0
 1 = {com.jjoe64.graphview.series.DataPoint@830038856272} "[1.428713481674E12/79.0]"
  x = 1.428713481674E12
  y = 79.0
 2 = {com.jjoe64.graphview.series.DataPoint@830038856400} "[1.428713482676E12/75.0]"
  x = 1.428713482676E12
  y = 75.0
 3 = {com.jjoe64.graphview.series.DataPoint@830038856528} "[1.428713483677E12/81.0]"
  x = 1.428713483677E12
  y = 81.0
 4 = {com.jjoe64.graphview.series.DataPoint@830038856656} "[1.428713484678E12/75.0]"
  x = 1.428713484678E12
  y = 75.0
 5 = {com.jjoe64.graphview.series.DataPoint@830038856784} "[1.428713485679E12/70.0]"
  x = 1.428713485679E12
  y = 70.0
 6 = {com.jjoe64.graphview.series.DataPoint@830038856912} "[1.428713486681E12/76.0]"
  x = 1.428713486681E12
  y = 76.0
 7 = {com.jjoe64.graphview.series.DataPoint@830038857040} "[1.428713487683E12/83.0]"
  x = 1.428713487683E12
  y = 83.0
 8 = {com.jjoe64.graphview.series.DataPoint@830038857168} "[1.428713488686E12/81.0]"
  x = 1.428713488686E12
  y = 81.0

I've also tried to set manually set the min and max x values, but that didn't help either. What could cause this problem?

**Comment by jjoe64** [comment]
please take a look at the example for dates
https://github.com/jjoe64/GraphView-Demos/blob/master/app/src/main/java/com/jjoe64/graphview_demos/fragments/DateAsXAxis.java

and if it does not help provide your complete code so i can test it

**Comment by zhouyu0615** [comment]
You encounter the  same problem as me, Beacuse the time Interval is too small ,you can try a large time interval ,say 1 minutes .  The details I describe in  https://github.com/jjoe64/GraphView/issues/342 
. I make a tempory solution .

**Comment by gary-realart** [comment]
I was able to reproduce the issue by shortening the interval in the example code:

```
public class DateAsXAxis extends Fragment {
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View rootView = inflater.inflate(R.layout.fragment_main, container, false);

        // generate Dates
        Calendar calendar = Calendar.getInstance();
        Date d1 = calendar.getTime();
        calendar.add(Calendar.SECOND, 1);
        Date d2 = calendar.getTime();
        calendar.add(Calendar.SECOND, 1);
        Date d3 = calendar.getTime();

        GraphView graph = (GraphView) rootView.findViewById(R.id.graph);

        // you can directly pass Date objects to DataPoint-Constructor
        // this will convert the Date to double via Date#getTime()
        LineGraphSeries<DataPoint> series = new LineGraphSeries<DataPoint>(new DataPoint[] {
                new DataPoint(d1, 1),
                new DataPoint(d2, 5),
                new DataPoint(d3, 3)
        });
        graph.addSeries(series);

        // set date label formatter
        graph.getGridLabelRenderer().setLabelFormatter(new DateAsXAxisLabelFormatter(getActivity()));
        graph.getGridLabelRenderer().setNumHorizontalLabels(3); // only 4 because of the space

        // set manual x bounds to have nice steps
        graph.getViewport().setMinX(d1.getTime());
        graph.getViewport().setMaxX(d3.getTime());
        graph.getViewport().setXAxisBoundsManual(true);

        return rootView;
    }

    @Override
    public void onAttach(Activity activity) {
        super.onAttach(activity);
        ((MainActivity) activity).onSectionAttached(
                getArguments().getInt(MainActivity.ARG_SECTION_NUMBER));
    }

}
```

**Comment by appsthatmatter** [comment]
closed, because too old. If the problem still exists, please reopen a new ticket.
