### ISSUE TITLE
Live Chart starting from the right hand side of the layout instead of left

### ISSUE THREAD

**Issue by Shivam101** [appsthatmatter/GraphView#331]
Hello,
I am using a live chart using the appendData() method. However, my graph starts from the right hand side of the layout and then grows towards the left. 
How can I make sure that it starts from the left like  it should ?
Also, the X-Axis doesn't start from 0, but from some arbitrary value(even though I have given minXValue=0). How do I ensure that it starts from 0 ?

Thanks !

**Comment by jjoe64** [comment]
are you sure that the values you give are coming in the correct order? the x-value must grow

**Comment by appsthatmatter** [comment]
closed, because too old. If the problem still exists, please reopen a new ticket.
