### ISSUE TITLE
Unexpected freeze with real time updates

### ISSUE THREAD

**Issue by sebap123** [appsthatmatter/GraphView#347]
My app requires drawing graph from real time data. I have thread with all the communication that is providing the data. In main thread I am reading this data and simply use mSeries1.appendData(new DataPoint(counter,data[0]),true,100); where counter is int that is incremented after each update.

Unfortunately at some point it freeze. I've tried putting it in synchronized block or changing the line of code to mSeries1.appendData(new DataPoint(counter,counter),true,100); and still this same result.

This is how the memory looks like during app running and when it freezes:
![memory](https://cloud.githubusercontent.com/assets/1652033/7691600/105e89f8-fdbc-11e4-9ce1-24c714067f3d.jpg)

Is that some library error or there is something wrong in my code?

**Comment by zhouyu0615** [comment]
Could you paste your  code  about   mSeries1 set, you counter is increase form 0 or other number? Maybe I can help you

**Comment by sebap123** [comment]
I guess everything what might be useful in describing this error can be found in this [SO question](http://stackoverflow.com/questions/30403513/difficulty-in-understanding-complex-multi-threading-in-android-app)

**Comment by zhouyu0615** [comment]
I have seen you quesion in stackflow, Maye my English is poor, I don't get  your project clearly. 
 My project is simialar to yours .
I advise you to do two things, 
      First of all ,you  can refer   http://www.android-graphview.org/documentation/category/realtime-updates , make sure the independent  demo code  is working correctly in your project. 
     Then,you can using your data which is send by Eventbus instead of demo data .using Logcat  to   wathch  every  graph  Points.  
If it can works correctly  at first step, but still wrong in second step.Pay attentinon to your  Data characteristics,.Is the X , Y value meet the graph's needs.  Wish you good luck !

**Comment by sebap123** [comment]
I did this example and as I wrote - it is working. The data has to work, correctly - I am constantly changing X and lib is only checking this value before drawing. Also logcat is not connected with UI so in this case values displayed there are useless.

**Comment by bmx666** [comment]
Using DataPoint object for allocation every time = wasting system resources and soooo slow.
I refactoring this library for better support realtime charts, where using only 2-dimensional arrays of doubles. Check my realtime branch [here](https://github.com/bmx666/GraphView/tree/realtime), where you can skip unusable validation and set required fixed size points.

**Comment by jjoe64** [comment]
memory leaks should be fixed already in version 4.1.0

**Comment by jjoe64** [comment]
=> introduce performance classes

**Comment by jjoe64** [comment]
=> provide documentation tips for large data
