### ISSUE TITLE
Bars on bar graph are not centered over labels

### ISSUE THREAD

**Issue by jordantrain** [appsthatmatter/GraphView#393]
Is there a way to position the bars in a bar graph so that bars after the first bar are centered over the x-axis values?  In my bar graph, the second bar appears to the right of the x-axis value.
![screenshot5](https://cloud.githubusercontent.com/assets/9443063/14231371/12b76728-f93e-11e5-9e28-7cf81c9f8cbb.png)
.

**Comment by jjoe64** [comment]
i think it's because of have multiple bar series?

**Comment by appsthatmatter** [comment]
closed, because too old. If the problem still exists, please reopen a new ticket.
