### ISSUE TITLE
No option to automatically maintain square Grid ratio 

### ISSUE THREAD

**Issue by alessandrodd** [appsthatmatter/GraphView#399]
There seems to be no option to _automatically_ adjust bounds in order to maintain 1:1 scale for x:y axis (and consequently to maintain an always-square grid).
Since this is a library to plot graphs, the lack of this feature means that every graph where the (visual) correspondence between x and y values is important gets shown in a distorted way.

Is there any temporary workaround besides defining the entire logic in order to make it work with automatic scaling and scrolling?

**Comment by jjoe64** [comment]
hi, you are right, there is no such feature and as far as i know there is no simple workaround to get it. fyi: if you need it you could use paid service. For paid service you can contact via http://www.android-graphview.org/get-support--license.html

**Comment by appsthatmatter** [comment]
closed, because too old. If the problem still exists, please reopen a new ticket.
