### ISSUE TITLE
setNumHorizontalLabels not working correctly in 4.1.0.

### ISSUE THREAD

**Issue by JDCGW** [appsthatmatter/GraphView#413]
Great library!  Thanks for the work you put in it.  Anyway, setNumHorizontalLabels is no longer working correctly in 4.1.0.  It works fine in 4.0.1.  I've attached my code and photos showing what happens.

```
graph.getViewport().setXAxisBoundsManual(true);
graph.getViewport().setMinX(10);
graph.getViewport().setMaxX(25);
graph.getGridLabelRenderer().setNumHorizontalLabels(6);
```

**4.0.1**
![4 0 1](https://cloud.githubusercontent.com/assets/20301504/16586934/e21df566-428d-11e6-8286-a5b558914925.png)

**4.1.0**
![4 1 0](https://cloud.githubusercontent.com/assets/20301504/16586939/e519770e-428d-11e6-8a0a-0c1822d8af62.png)

*Edited 03/09/17 - Changed from setNumVerticalLabels to setNumHorizontalLabels, as setNumHorizontalLabels is really working incorrectly.

**Comment by JDCGW** [comment]
I've just tested 4.2.1, and this is still not working FYI.

**Comment by maydin** [comment]
@JDCGW in your code you set vertical label count. But in your screenshots, horizontal label counts are changing. Am i missing something?

**Comment by JDCGW** [comment]
@maydin You're correct!  I meant setNumHorizontalLabels, not setNumVerticalLabels.  Anyway, I've updated the original post, and I've retested.  The setNumHorizontalLabels is still not working correctly past 4.0.1.

**Comment by maydin** [comment]
It seems this is not a bug, this is a feature :)
If you disable humanReading, you can get the same number of labels with 4.0.1. I executed your sample with disabling humanRounding.
graph.getGridLabelRenderer().setHumanRounding(false);
@appsthatmatter could you please confirm?

**Comment by JDCGW** [comment]
@maydin Thank you!  That fixed the issue.
