### ISSUE TITLE
Incorrect calculation of CompleteRange in Viewport and SecondScale

### ISSUE THREAD

**Issue by bmx666** [appsthatmatter/GraphView#439]
Logical issue: if first series empty, then using wrong **mCompleteRange**, because it skip get min/max X/Y values of other series.

Code correction:
1. Copy-paste issue in body of function **calcCompleteRange**  in **SecondScale.java**
`if (!series.isEmpty() && !series.get(0).isEmpty()) {`
check same condition twice
2. Improve code readability and removes boilerplate code of 4 loops.

**Comment by jjoe64** [comment]
i will check thx
