### ISSUE TITLE
ViewPort background color

### ISSUE THREAD

**Issue by Rosmkr** [appsthatmatter/GraphView#444]
When I set the background color for ViewPort  graph.getViewPort().setBackgroundColor(Color.Black)
It fill a legend color too.How fill background color only to ViewPort, square where pain the GraphLine?
I use GraphView-4.2.1.jar library.There is no issue in library GraphView-4.0.1.jar.

**Comment by jjoe64** [comment]
i will check

**Comment by appsthatmatter** [comment]
its possible with
        graph.getLegendRenderer().setBackgroundColor(Color.argb(150, 50, 0, 0));
