### ISSUE TITLE
Ontap listner for First point

### ISSUE THREAD

**Issue by Ashu-yo** [appsthatmatter/GraphView#446]
ontap listner is not working for first value in linegraph and the values after the NAN values. Kindly help..

**Comment by jjoe64** [comment]
i will check

**Comment by Ashu-yo** [comment]
TapListner for first point can be enabled by registering the datapoint by adding register datapoint after 
line no. 451 canvas.drawCircle(first_X, first_Y, mStyles.dataPointsRadius, paint);
                     registerDataPoint(first_X, first_Y, value);

To draw datapoints for when the previous value is null then the following need to be added after 
line no. 472

if (!skipDraw && !Float.isNaN(endY) && Float.isNaN(startY)) {

                   if (mAnimated) {

                        if ((Double.isNaN(mLastAnimatedValue) || mLastAnimatedValue < valueX)) {
                            long currentTime = System.currentTimeMillis();
                            if (mAnimationStart == 0) {
                                // start animation
                                mAnimationStart = currentTime;
                                mAnimationStartFrameNo = 0;
                            } else {
                                // anti-lag: wait a few frames
                                if (mAnimationStartFrameNo < 15) {
                                    // second time
                                    mAnimationStart = currentTime;
                                    mAnimationStartFrameNo++;
                                }
                            }
                            float timeFactor = (float) (currentTime-mAnimationStart) / ANIMATION_DURATION;
                            float factor = mAnimationInterpolator.getInterpolation(timeFactor);
                            if (timeFactor <= 1.0) {
                                startXAnimated = (startX-lastAnimationReferenceX) * factor + lastAnimationReferenceX;
                                startXAnimated = Math.max(startXAnimated, lastAnimationReferenceX);
                                endXAnimated = (endX-lastAnimationReferenceX) * factor + lastAnimationReferenceX;
                                ViewCompat.postInvalidateOnAnimation(graphView);
                            } else {
                                // animation finished
                                mLastAnimatedValue = valueX;
                            }
                        } else {
                            lastAnimationReferenceX = endX;
                        }

                    }


                    // draw data point
                    if (!isOverdrawEndPoint) {

                        if (mStyles.drawDataPoints) {
                            // draw datapoint for values after NAN values
                            Paint.Style prevStyle = paint.getStyle();
                            paint.setStyle(Paint.Style.FILL);
                            canvas.drawCircle(endXAnimated, endY, mStyles.dataPointsRadius, paint);
                            paint.setStyle(prevStyle);
                            registerDataPoint(endX, endY, value);

                        }

                    }


                 
                    if (mDrawAsPath) {
                        Log.i("LineGraphView","mDrawAsPath...");

                        mPath.moveTo(startXAnimated, startY);
                    }
                    // performance opt.
                    if (Math.abs(endX-lastRenderedX) > .3f) {
                        
                        if (mDrawAsPath) {
                            mPath.lineTo(endXAnimated, endY);
                        } else {
                            renderLine(canvas, new float[] {startXAnimated, startY, endXAnimated, endY}, paint);
                        }
                        lastRenderedX = endX;
                    }

                }

I'm not sure if this will end up being an issue (i.e., these changes were made to fix bug) correct me if i am wrong. i have uploaded the file
[LineGraphSeries - Shortcut.zip](https://github.com/jjoe64/GraphView/files/612495/LineGraphSeries.-.Shortcut.zip)

**Comment by yueyangz** [comment]
Found the same issue, but glad somebody brought it up.

**Comment by appsthatmatter** [comment]
i think it is fixed in the meantime
