### ISSUE TITLE
real-time add data,the graph doesn't right.

### ISSUE THREAD

**Issue by joy-chen** [appsthatmatter/GraphView#449]
![screenshot_20161124-133607](https://cloud.githubusercontent.com/assets/3357420/20587837/8ebbd8ce-b24b-11e6-993c-c058198cf1cb.jpg)
please check the photo
it just show up on MTK device.

**Comment by jjoe64** [comment]
is there a way you can give me the source code so that I can exactly test this and fix it?

**Comment by joy-chen** [comment]
@jjoe64 I just install the GraphView demo in MTK device, [source](https://github.com/jjoe64/GraphView-Demos/blob/master/app/src/main/java/com/jjoe64/graphview_demos/categories/RealtimeFragment.java)

**Comment by jjoe64** [comment]
need some device to reproduce it...

**Comment by joy-chen** [comment]
Hi, this could be reproduce on any devices using MTK cpu.

**Comment by Alwaysso** [comment]
How to solve the problem

**Comment by appsthatmatter** [comment]
related to #499

**Comment by appsthatmatter** [comment]
@joy-chen @Alwaysso 
I did an update, but since I cannot reproduce the problem I ask you to check if it's looking good now, on the devices? I updated the GraphView Demos app in Google Play. So could you please verify?

**Comment by appsthatmatter** [comment]
should be fixed
