### ISSUE TITLE
Dates make numHorizontalLabels overflow

### ISSUE THREAD

**Issue by Erhannis** [appsthatmatter/GraphView#451]
For some of my graphs with dates on the horizontal axis, the library freezes up.  My debugging leads me to the following theory.
This takes place in (GridLabelRenderer).adjustHorizontal().
1.  The graph is first drawn with a viewport of width 1.  This populates mStepsHorizontal with steps of size, e.g., 0.25.
2.  Then the true scale of the graph kicks in and it begins recalculating.
3.  However, lines 828-876 maintain the step size of 0.25, which leads numHorizontalLabels to be set to a massive value on line 896.
4.  Depending on the dates, this value can wrap around into the negatives, in which case the loop isn't processed and the code does not freeze.
5.  If you skip the erroneously huge loop, bypassing the freeze, the next time adjustHorizontal() gets called (as well as all successive times, apparently), exactSteps is an appropriate value (through a mechanism I have not investigated), and you get the expected number of labels.

So, if either the root problem can be found and fixed, or if you simply skip the loop at the end of adjustHorizontal() when the number of labels > 1000 or so, that could probably fix it.

**Comment by Erhannis** [comment]
I think (GridLabelRenderer).adjustVertical() suffers from a similar problem, though the numbers involved only give you thousands of vertical labels, instead of the millions of labels encountered with dates, so it doesn't freeze.

**Comment by appsthatmatter** [comment]
closed, because too old. If the problem still exists, please reopen a new ticket.
