### ISSUE TITLE
cannot display graph when the entry is too large

### ISSUE THREAD

**Issue by bertojk** [appsthatmatter/GraphView#452]
Hello there. I am developing a software for statistic simulation. I am really impressed that I found this library  for graph plotting since it's really easy to understand. 

For now, I am dealing with large data. I am creating a random generator from 0 to 100 in double with one decimal. With 10 entries, it can be displayed in bar chart but it's blank when I have 30 entries or more. My guess is because it can't handle much entry. Maybe in the future, i wanna use 1000 entries. Hope you can give me solution or maybe another class to handle this large data.

**Comment by jjoe64** [comment]
to display large amount of data then it's better to use line graph series. Is this a option for you, or do you need to use bars?

**Comment by bertojk** [comment]
Yes, i need to use bar chart

**Comment by jpberry** [comment]
I've had the same issue, but I tought it was normal : when you add too many X values, you end up with the width of the bar being too small for the screen (you can see the bars dissapear and reappear when you use horizontal scaling). Solution I took : group data : for instance, I have a rainfall data per hour, I can group it by day or week, and then see the data in a bar chart over a longer period of time.

**Comment by appsthatmatter** [comment]
closed, because too old. If the problem still exists, please reopen a new ticket.
