### ISSUE TITLE
ScrollView causes problems

### ISSUE THREAD

**Issue by Erhannis** [appsthatmatter/GraphView#453]
Currently, if you put a scrollable graph somewhere in a ScrollView, they don't work too well together.  Attempting to scroll or zoom on the graph tends to just scroll the scrollview.  You can (with great care and difficulty) scroll the graph vertically, a little at a time, but it's a pain.

I realize that ScrollView itself suffers from similar issues, so I'm not actually surprised that the graph does, too.  Android has come out with a [NestedScrollView](https://developer.android.com/reference/android/support/v4/widget/NestedScrollView.html), though, so maybe you could interface with that, so the graphs could still be scrolled when inside a NestedScrollView.

**Comment by appsthatmatter** [comment]
closed, because too old. If the problem still exists, please reopen a new ticket.

**Comment by joshysav** [comment]
This does not directly relate to the GraphView but what is possible it to lock the scroll view when interacting with the graph. 


`
public class LockableScrollView extends ScrollView {

    // true if we can scroll (not locked)
    // false if we cannot scroll (locked)
    private boolean mScrollable = true;

    public LockableScrollView(Context context) {
        super(context);
    }

    public LockableScrollView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public LockableScrollView(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
    }

    public LockableScrollView(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
        super(context, attrs, defStyleAttr, defStyleRes);
    }

    public void setScrollingEnabled(boolean enabled) {
        mScrollable = enabled;
    }

    public boolean isScrollable() {
        return mScrollable;
    }

    @Override
    public boolean onTouchEvent(MotionEvent ev) {
        switch (ev.getAction()) {
            case MotionEvent.ACTION_DOWN:
                // if we can scroll pass the event to the superclass
                return mScrollable && super.onTouchEvent(ev);
            default:
                return super.onTouchEvent(ev);
        }
    }

    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        // Don't do anything with intercepted touch events if
        // we are not scrollable
        return mScrollable && super.onInterceptTouchEvent(ev);
    }

}`

Hope this is off help!
