### ISSUE TITLE
min/max bar chart

### ISSUE THREAD

**Issue by jpberry** [appsthatmatter/GraphView#454]
Is it possible to display min/max values ?

What I would need would be very simple : it's just a bar chart, but instead of having each bar extend from the X-axis to the given value {Y=0 -> Y=f(x)}, the bar would extend between a given min and a max Y value {Y=fmin(x) -> Y=fmax(x).

In short, it's a slight extension of the current bar graph, allowing to define a non-zero value for the starting point of the bar.

**Comment by appsthatmatter** [comment]
closed, because too old. If the problem still exists, please reopen a new ticket.
