### ISSUE TITLE
Not able to save graphview as an image

### ISSUE THREAD

**Issue by sps9** [appsthatmatter/GraphView#455]
I am trying to save a graphview as an image.  
The issue I am facing is- The file created is an empty file. Its size is 0B. 
I think the problem is that the file is created before the graph is plotted.
Can someone help me out with this issue.
The code I used is as follows:

    `public class MainActivity extends AppCompatActivity {
    LinearLayout ll;
    Bitmap bitmap;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_mainn);
        final GraphView graphView = (GraphView) findViewById(R.id.graph);
        LineGraphSeries<DataPoint> series = new LineGraphSeries<DataPoint>(new DataPoint[]{
                new DataPoint(0, 1),
                new DataPoint(1, 5),
                new DataPoint(2, 3),
                new DataPoint(3, 2),
                new DataPoint(4, 6)
        });
        graphView.addSeries(series);
        RelativeLayout rl = (RelativeLayout) findViewById(R.id.myLayout);
        rl.setDrawingCacheEnabled(true);
        bitmap = rl.getDrawingCache();
        rl.setDrawingCacheEnabled(false);
        File file,f;
        if (android.os.Environment.getExternalStorageState().equals(android.os.Environment.MEDIA_MOUNTED))
        {
            file =new File(android.os.Environment.getExternalStorageDirectory(),"GRAPHS_PLOTTED");
            if(!file.exists())
            {
                file.mkdirs();
            }
            try{
                f = new File(file.getAbsolutePath()+file.separator+ "name"+".jpg");
                FileOutputStream ostream = new FileOutputStream(f);
               bitmap.compress(Bitmap.CompressFormat.PNG, 10, ostream);
                ostream.close();
            }
            catch (Exception e){
                e.printStackTrace();
            }
        }

    }
    }`

**Comment by manurs** [comment]
I need to save the graph too.
Did you get a solution?

Thanks!

**Comment by appsthatmatter** [comment]
closed, because too old. If the problem still exists, please reopen a new ticket.
