### ISSUE TITLE
Horizontal Labels Disappear When Scrolling

### ISSUE THREAD

**Issue by dmacpro91** [appsthatmatter/GraphView#459]
Had an issue where the last of my horizontal labels would disappear when scrolling.  Resolved with this simple fix in GridLabelRenderer highlighted in the image attached.

<img width="897" alt="screen shot 2016-12-28 at 10 48 52 pm" src="https://cloud.githubusercontent.com/assets/2788893/21536343/dc3cd3e0-cd4f-11e6-8911-ec6b59665e75.png">

**Comment by appsthatmatter** [comment]
closed, because too old. If the problem still exists, please reopen a new ticket.
