### ISSUE TITLE
GraphView doesnt work on Lenovo device with Android 4.4.2

### ISSUE THREAD

**Issue by PrimakPavel** [appsthatmatter/GraphView#463]
I use this library for creation of graphics in a project. I checked it on many different devices and it works on all of them except Lenovo with Android 4.4.2 (two devices Lenovo 7'' and Lenovo 10''). My boss told me to use another libs because he reckons this one has a problem. But I like GraphView and ask you to fix this problem as soon as possible, please)

**Comment by PrimakPavel** [comment]
Layout is created but all series (Line Graph Series) are invisible.

**Comment by jjoe64** [comment]
thanks for reporting I will check asap. did you test the official graphview demos app?

**Comment by PrimakPavel** [comment]
Thanks for reaction). No I didn't test it with official graphview demos app, but I tested it with simply graphs. It work at all device with API 19, except Lenovo

**Comment by appsthatmatter** [comment]
should be fixed
