### ISSUE TITLE
GraphView with dates getX value

### ISSUE THREAD

**Issue by sahargal** [appsthatmatter/GraphView#466]
i have graph with date asXAxis when i want to display the data from the point my log show:
I/dateX:: 1.48478689E12
I/dateX:: 1.484841583E12
I/dateX:: 1.4784696E12
I/dateX:: 1.4516856E12
I/dateX:: 1.48481168E12
how can i retrieve the date data from the point?..

**Comment by appsthatmatter** [comment]
new Date(....)
