### ISSUE TITLE
Getting IllegalStateException when trying to take snapshot of the graph

### ISSUE THREAD

**Issue by ksdeo** [appsthatmatter/GraphView#474]
I'm trying to take snapshot of the GraphView but it gives an error "GraphView must be used in hardware accelerated mode."
I'm using the following code to take snapshot
`Bitmap bitmap = Bitmap.createBitmap(view.getWidth(),
                view.getHeight(), Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bitmap);
        view.draw(canvas);`

Also, i've already set `android:hardwareAccelerated="true"` at application level.

**Comment by kb0** [comment]
@ksdeo You can try to use this workaround - http://stackoverflow.com/questions/41920458/getting-illegalstateexception-when-trying-to-take-snapshot-of-the-graph-for-http/42222784#42222784

**Comment by appsthatmatter** [comment]
thanks for your support @kb0

**Comment by caseymongoven** [comment]
This workaround does not actually work, nor do several other things I have tried. Does anybody have any other ideas? I'm sure lots of people who use GraphView would like to be able to create an image from their graphs.

**Comment by julespi** [comment]
Are there any news of this bug? I would really like to be fixed

**Comment by matiasalejandro** [comment]
![loadgraphviewmodule](https://user-images.githubusercontent.com/24846252/37405994-dd66dd1c-2774-11e8-8d83-589843c98af5.png)


takeSnapshotAndShare

**Comment by appsthatmatter** [comment]
need a new release
