### ISSUE TITLE
Incorrect draw lines

### ISSUE THREAD

**Issue by Kualkua9000** [appsthatmatter/GraphView#477]
Hi! Can you help me with a little problem? What could it be?

http://prntscr.com/e8793b

http://prntscr.com/e879c1

Thanks!

**Comment by Kualkua9000** [comment]
It is observed not on all devices. For example on the Lenovo P70-A and the tablet Samsung Galaxy Tab 2 is not displayed correctly, but on the Xiaomi Readmi Note 3 & Xiaomi Redmi 3 - all is well.

**Comment by appsthatmatter** [comment]
thanks for the details. i need to investigate

**Comment by appsthatmatter** [comment]
can this problem reproduced with the official GraphView-Demos app from the Play Store?

**Comment by Kualkua9000** [comment]
I checked in the program, there is an error. Thank you to pay attention.

http://prntscr.com/eee8cl

**Comment by Boshoff93** [comment]
I am having the same issue using a Samsung Galaxy Tab 2

**Comment by appsthatmatter** [comment]
same issue with Samsung edge

**Comment by appsthatmatter** [comment]
related to #499

**Comment by appsthatmatter** [comment]
@Boshoff93 @Kualkua9000 
I did an update, but since I cannot reproduce the problem I ask you to check if it's looking good now, on the devices? I updated the GraphView Demos app in Google Play. So could you please verify?

**Comment by appsthatmatter** [comment]
should be fixed
