### ISSUE TITLE
Failed to resolve 'com.jjoe64:graphview:4.0.1'

### ISSUE THREAD

**Issue by pluto20010** [appsthatmatter/GraphView#481]
Hello, I am a complete newbie in android and wanted to use the GraphView library.
As stated I just wrote com.jjoe64:graphview:4.0.1 in the dependancies in GradleScrips>build.gradle(Module:app)>dependencies

it asked be to sync gradle
but it shows the above message
Failed to resolve 'com.jjoe64:graphview:4.0.1'

What am I doing wrong?

**Comment by ffischer1984** [comment]
`    compile 'com.jjoe64:graphview:4.2.1'` in the dependencies works at my project

**Comment by appsthatmatter** [comment]
should work

**Comment by rossHell** [comment]
@appsthatmatter so useful reply....
