### ISSUE TITLE
Links to documentation links for GraphView not working?

### ISSUE THREAD

**Issue by qlister** [appsthatmatter/GraphView#483]
The links from your documentation on http://www.android-graphview.org to the GitHub site are broken.

Example:
From
http://www.android-graphview.org/line-graph/
The LineGraphSeries class link which is:
http://jjoe64.github.io/GraphView/javadoc/com/jjoe64/graphview/series/LineGraphSeries.html
has a 404 page error.

Is this a simple fix?

Best regards,

Quentin Lister

**Comment by appsthatmatter** [comment]
thanks for reporting! i just fixed it
