### ISSUE TITLE
Labelformatter xValues increases 2 each step?

### ISSUE THREAD

**Issue by JamesLeit** [appsthatmatter/GraphView#498]
Hi,

I just started testing GraphView. - I got dynamically generated X and Y values and want to replace the X values in my custom LabelFormatter with Strings; But I can't use an Array or List to get the Labels for the LabelFormatter, because the X values starts at 0 and each step 2 values bigger (0, 2, 4, 6,..).
Did I something wrong?

I just created a LineGraphSeries and added 12 Datapoints ( and changed the labelcount to 12).

**Comment by appsthatmatter** [comment]
the labels needs to be dynamic because they need to be regenerated depending on the viewport. Imagine the user scrolls or zooms in.
If you want real static labels take a look at the [static labels](http://www.android-graphview.org/static-labels/)
