### ISSUE TITLE
Horizontal Bargraph

### ISSUE THREAD

**Issue by felipheggaliza** [appsthatmatter/GraphView#511]
Does this API support horizontal bar graph?

**Comment by Asymons** [comment]
I don't think so, but my hack solution was 

(Kotlin)
`graph.rotation = 90f`

(Java)
`graph.setRotation(90f);`

Then, you should be able to hide and rotate the labels to make it into a horizontal bar graph. Hope this helped!

**Comment by appsthatmatter** [comment]
thx
