### ISSUE TITLE
Need to add custom grid to the background of the graph which zoom with aspect ratio 

### ISSUE THREAD

**Issue by munasinghecm** [appsthatmatter/GraphView#512]
I'm using Graphview to plot ECG signal. So I need to add standard ECG grid to the background of the graph. I added a grid by using 
 `graph.getGridLabelRenderer().setNumHorizontalLabels(7);
  graph.getGridLabelRenderer().setNumVerticalLabels(7);`
But the aspect ratio of the grid move away while zooming. So how can I fix this issue. Also how can I scroll the graph without zooming in horizontal axis.

**Comment by appsthatmatter** [comment]
disable scaling
