### ISSUE TITLE
Not showing all DataPoints

### ISSUE THREAD

**Issue by sbarak** [appsthatmatter/GraphView#514]
Hello,

For some reason, not **all** DataPoint in a simple LineGraph are shown on screen.
 
`        LineGraphSeries<DataPoint> test_series = new LineGraphSeries<DataPoint>(new DataPoint[]{

                new DataPoint(1,1),
                new DataPoint(3,2),
                new DataPoint(5,3),
                new DataPoint(7,10),
                new DataPoint(9,3),
                new DataPoint(11,2),
                new DataPoint(30,1),
                new DataPoint(40,1)

        });
        test_series.setDrawDataPoints(true);
        draw_series(test_series);`

The last two DataPoints are not shown. X-Axis reaches to 20 approximately.

my xml file is the basic:

`<?xml version="1.0" encoding="utf-8"?>
    <com.jjoe64.graphview.GraphView xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/graph"/>`

The DataPoints are stored OK in "test_series" variable. But the graph is not getting drawn all the way...
![1](https://cloud.githubusercontent.com/assets/29093508/26628603/619bbda0-4607-11e7-87c8-a5f791879f46.png)

**Comment by appsthatmatter** [comment]
looks like you have set a manual viewport to max 20

**Comment by sbarak** [comment]
No, I did not set any manual settings. Only the code you saw above. 
I noticed that if the DataPoints are "far away" on the x-axis, the graph doesn't show it. 
In the example above, the x=30 and x=40 are "far" from the previous DataPoints.

**Comment by appsthatmatter** [comment]
can you try to disable human rounding:

`mGraph.getGridLabelRenderer().setHumanRounding(false);`

**Comment by sbarak** [comment]
That didn't work.
I had to setXAxisBoundsManual(true) and I set the X axis manually - **That seems to work this way**.
Maybe something is wrong with the automated scaling...

**Comment by exoji2e** [comment]
I got a similar error, where my line graph also gets cut off at x=20.
It works to set manually, but is annoying. For anyone visiting this in the future, what @sbarak means is:
```
double max_x = 32.0; // or max(datapoints.x)
mgraph.getViewport().setXAxisBoundsManual(true);
mgraph.getViewport().setMaxX(max_x);
```

**Comment by m-jayy** [comment]
same error... anyone fixed this issue?
