### ISSUE TITLE
Showing too many points on the y-axis.

### ISSUE THREAD

**Issue by Jakkaps** [appsthatmatter/GraphView#515]
I have dates as x-axis and weight in kg as y-axis. The graph is set up in a fragment. You can add new graphs to the graphview by entering the name of the graph in an autocompletextview:
       
 ```
        DateFormat dateFormat = android.text.format.DateFormat.getDateFormat(getActivity());
        DateAsXAxisLabelFormatter dateAsXAxisLabelFormatter = new 
        DateAsXAxisLabelFormatter(getActivity(), DateFormat.getDateInstance());
        graphView.getGridLabelRenderer().setLabelFormatter(dateAsXAxisLabelFormatter);
        graphView.getGridLabelRenderer().setNumHorizontalLabels(3);// only 4 because of the space
        graphView.getGridLabelRenderer().setHumanRounding(false);
        graphView.getViewport().setXAxisBoundsManual(true);
        graphView.getViewport().setYAxisBoundsManual(false);

        String[] names= getNames();
        ArrayAdapter<String> adapter = new ArrayAdapter<>(getActivity(), 
        android.R.layout.simple_dropdown_item_1line, names);
        addGraphValue.setAdapter(adapter);

        addGraphValue.setOnEditorActionListener(new TextView.OnEditorActionListener() {
            @Override
            public boolean onEditorAction(TextView v, int actionId, KeyEvent event) {
                if (actionId == EditorInfo.IME_ACTION_SEARCH){
                    addToGraph(addGraphValue.getText().toString());
                }
                return true;
            }
        }); 
```

The addToGraph performs a function where a y-value is found based on some criteria, regarding the text in the addGraphValue autoCompleteTextview. When that value is found, it is added to a lineGraphSeries together with its corresponding date. After that has happened as many times as it has to, the series is added to the graph:
               
 ```
               for(/*not important*/){
                    //Finding the y-value
                    dataPoint = new DataPoint(date, y);
                    mLineGraphSeries.appendData(dataPoint, false, 100);
                }

                mLineGraphSeries.setColor(mColors[position]);
                graphView.addSeries(mLineGraphSeries);
                mLineGraphSeries.setDrawDataPoints(true);
```
So here comes the problem, when the first value is added, the y-axis goes crazy and adds way to many values:
![phone at bug](https://cloud.githubusercontent.com/assets/11243783/26664931/f6ac21b2-4695-11e7-85ad-85b660e44e64.png)

Now if i turn on human rounding, the y-values are fixed but the dates are displayed weirdly:
![phone at bug 2](https://cloud.githubusercontent.com/assets/11243783/26664980/86d09354-4696-11e7-8ddd-d634f8b75532.png)

If I reload the page(saving the linegraphseries, reloading the fragment and adding it again), the problem is no longer there. For the life of me I can not figure out what is wrong, please help.

**Comment by silentbank** [comment]
I have the same issue, I am using dates in the x axis. Any idea ?

**Comment by VMitin** [comment]
`public class CustomGraphView extends GraphView {
    public CustomGraphView(Context context) {
        super(context);
    }

    public CustomGraphView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public CustomGraphView(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
    }

    public void init() {
        super.init();
    }
}
`

And call init() before redraw the graph

**Comment by woelfelm** [comment]
Fantastic answer, thanks.

**Comment by VMitin** [comment]
I found that the mStepsHorizontal in the GridLabelRenderer is not cleared first time when you try to draw another graph. So the steps between points calculated with the mistake. 

I found only one solution. Override the GraphView and call init() before drawing another graph (for recreating the GridLabelRenderer).

**Comment by AndroidAsh5** [comment]
Thank you soo much @VMitin ..After headache of 2 days.. I finally found a solution with your answer
