### ISSUE TITLE
Realtime X axis with amount of time passed

### ISSUE THREAD

**Issue by jfjallid** [appsthatmatter/GraphView#516]
Hello!

I'm working with real time data and get sensor values every 30 seconds and would like to continuosly update the graph with new data as well as the min and max X and Y values. The X axis should contain labels such as:
2 days 3 hours, 1 hour 2 min, 3 min 30 sec ago,  30 sec ago 
etc. depending on the timestamp of the received data.

I can get these labels by creating my own LabelFormatter and overriding formatLabel but the problem is the Max and Min labels on the X and Y  axis.
I have a thread running that updates the data series every 30 seconds with the most recent values using the resetData() method, but I can't get the limit methods to update the limits periodically based on the current dataset.
graph.getViewport().setMinY()
graph.getViewport().setMinX()
graph.getViewport().setMaxY()
graph.getViewport().setMaxX()

**Comment by appsthatmatter** [comment]
seems to be a support ticket and not directly a bug within the lib
