### ISSUE TITLE
Anyone successfully export image from graph?

### ISSUE THREAD

**Issue by caseymongoven** [appsthatmatter/GraphView#517]
Has anyone been able to successfully export an image from a graph? If so, how did you do it? All attempts I have made have resulted in the error:

"java.lang.IllegalStateException: GraphView must be used in hardware accelerated mode.You can use android:hardwareAccelerated="true" on your activity."

But the suggested solution does not actually make any difference. This issue has also been discussed in other places (https://github.com/appsthatmatter/GraphView/issues/490), but perhaps somebody has a different method of creating an image from a graph that actually worked?

**Comment by appsthatmatter** [comment]
You have to use the current code from the master branch. There is a
build-in export function.

**Comment by caseymongoven** [comment]
Excellent, thank you so much.
