### ISSUE TITLE
setNumHorizontalLabels works inconsistently

### ISSUE THREAD

**Issue by Rexios80** [appsthatmatter/GraphView#518]
I am attempting to have several graphs scroll simultaneously using a seek bar. I also have a spinner to select the size of the viewport. The horizontal axis labels are dates. I have set the number of horizontal labels to five. The graph starts out with the correct number of horizontal labels, and certain sizes work consistently. Larger viewports frequently do not have the correct number of labels. There are upwards of 3000 points of data in total​ for each graph. Maybe this is related to the issue. This issue is very inconsistent. Sometimes the number of labels is correct, others it is some seemingly random number.

**Comment by appsthatmatter** [comment]
pls provide more detailed example with code to reproduce
