### ISSUE TITLE
Customize Horizontal Label Step and label title problem

### ISSUE THREAD

**Issue by thezukkino** [appsthatmatter/GraphView#519]
I need to customize Horizontal label step of 252 x-values.
The plugin automatically adjust my x-values with 200 x-values step. Is there any way to force the label step without re-implementing the adjust method?
The second problem appears when I set label title to Y: the graph scrolls horizontally and goes out the screen. 

Thanks for the support

**Comment by appsthatmatter** [comment]
pls see documentation about viewport and labels
http://www.android-graphview.org/basics-of-graphview/
