### ISSUE TITLE
Line Graph UI is Jumpy

### ISSUE THREAD

**Issue by apurvas** [appsthatmatter/GraphView#526]
![graphpicture](https://user-images.githubusercontent.com/9341913/28449957-00f123dc-6d99-11e7-9152-dcfe369c6818.png)
In the above picture the line isnt smooth. Is there a fix around this that I don't know about? Ideally even if the x-axis coordinates are about the same you would be expecting a vertical line. In this case it looks like whenever the x-axis coordinates are reasonably close the line graph jumps.

**Comment by Ubmeje** [comment]
What version do you run?
Maybe this is the same. #448

**Comment by appsthatmatter** [comment]
should be fixed in the meantime
