### ISSUE TITLE
Not plotting same x-values on the end of the line.

### ISSUE THREAD

**Issue by Ubmeje** [appsthatmatter/GraphView#527]
The #448 issue fix works great for me but i think I found another problem.
If the line make a "90 degrees hook" in the end it dont plot.
I running the master version.

Example:

            new DataPoint(0, 1),
            new DataPoint(1, 1),
            new DataPoint(1, 2),

**Comment by appsthatmatter** [comment]
it is not allowed to have 2 datapoints on the same x value
