### ISSUE TITLE
Trying to create a graph with dynamic max y value and static min y value of 0 

### ISSUE THREAD

**Issue by eng20000** [appsthatmatter/GraphView#528]
Hi :),
I'm trying to create a graph with dynamic values for y axis but i want the the min y axis value will always start from 0.
How can I set dynamic graph to always show y axis from 0?

Thanks a lot
David

**Comment by Ubmeje** [comment]
Maybe you could draw an extra line that is invisible and always have zero y-value.

**Comment by eng20000** [comment]
Thanks Ubmeje, Good idea! 
I will try it.
