### ISSUE TITLE
Unknown Inflation Error from XML

### ISSUE THREAD

**Issue by dmakimdt** [appsthatmatter/GraphView#531]
> Process: ca.mdt.mdtsmartapp, PID: 8097
>                                                                    java.lang.RuntimeException: An error occurred while executing doInBackground()
>                                                                        at android.os.AsyncTask$3.done(AsyncTask.java:309)
>                                                                        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
>                                                                        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
>                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
>                                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
>                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>                                                                        at java.lang.Thread.run(Thread.java:818)
>                                                                     Caused by: android.view.InflateException: Binary XML file line #59: Binary XML file line #59: Error inflating class com.jjoe64.graphview.GraphView
>                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
>                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
>                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
>                                                                        at ca.mdt.mdtsmartapp.ui.activity.LinkFEFActivity.setLayoutAndStartReading(LinkFEFActivity.java:838)
>                                                                        at ca.mdt.mdtsmartapp.ui.activity.LinkFEFActivity.onInstrumentSelected(LinkFEFActivity.java:810)
>                                                                        at ca.mdt.mdtsmartapp.ui.activity.LinkFEFActivity.isSMARTorLegacy(LinkFEFActivity.java:1031)
>                                                                        at ca.mdt.mdtsmartapp.ui.activity.LinkFEFActivity.access$4000(LinkFEFActivity.java:108)
>                                                                        at ca.mdt.mdtsmartapp.ui.activity.LinkFEFActivity$openDevice.doInBackground(LinkFEFActivity.java:2694)
>                                                                        at ca.mdt.mdtsmartapp.ui.activity.LinkFEFActivity$openDevice.doInBackground(LinkFEFActivity.java:2276)
>                                                                        at android.os.AsyncTask$2.call(AsyncTask.java:295)
>                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>                                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
>                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
>                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
>                                                                        at java.lang.Thread.run(Thread.java:818) 
>                                                                     Caused by: android.view.InflateException: Binary XML file line #59: Error inflating class com.jjoe64.graphview.GraphView
>                                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:657)
>                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
>                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
>                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
>                                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
>                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
>                                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
>                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
>                                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
>                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
>                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
>                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
>                                                                        at ca.mdt.mdtsmartapp.ui.activity.LinkFEFActivity.setLayoutAndStartReading(LinkFEFActivity.java:838) 
>                                                                        at ca.mdt.mdtsmartapp.ui.activity.LinkFEFActivity.onInstrumentSelected(LinkFEFActivity.java:810) 
>                                                                        at ca.mdt.mdtsmartapp.ui.activity.LinkFEFActivity.isSMARTorLegacy(LinkFEFActivity.java:1031) 
>                                                                        at ca.mdt.mdtsmartapp.ui.activity.LinkFEFActivity.access$4000(LinkFEFActivity.java:108) 
>                                                                        at ca.mdt.mdtsmartapp.ui.activity.LinkFEFActivity$openDevice.doInBackground(LinkFEFActivity.java:2694) 
>                                                                        at ca.mdt.mdtsmartapp.ui.activity.LinkFEFActivity$openDevice.doInBackground(LinkFEFActivity.java:2276) 
>                                                                        at android.os.AsyncTask$2.call(AsyncTask.java:295) 
>                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
>                                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
>                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
>                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
>                                                                        at java.lang.Thread.run(Thread.java:818) 
>                                                                     Caused by: java.lang.reflect.InvocationTargetException
>                                                                        at java.lang.reflect.Constructor.newInstance(Native Method)
>                                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:631)
>                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
>                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
>                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
>                                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
>                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
>                                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
>                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
>                                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
>                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
>                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
>                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
>                                                                        at ca.mdt.mdtsmartapp.ui.activity.LinkFEFActivity.setLayoutAndStartReading(LinkFEFActivity.java:838) 
>                                                                        at ca.mdt.mdtsmartapp.ui.activity.LinkFEFActivity.onInstrumentSelected(LinkFEFActivity.java:810) 
>                                                                        at ca.mdt.mdtsmartapp.ui.activity.LinkFEFActivity.isSMARTorLegacy(LinkFEFActivity.java:1031) 
>                                                                        at ca.mdt.mdtsmartapp.ui.activity.LinkFEFActivity.access$4000(LinkFEFActivity.java:108) 
>                                                                        at ca.mdt.mdtsmartapp.ui.activity.LinkFEFActivity$openDevice.doInBackground(LinkFEFActivity.java:2694) 
>                                                                        at ca.mdt.mdtsmartapp.ui.activity.LinkFEFActivity$openDevice.doInBackground(LinkFEFActivity.java:2276) 
>                                                                        at android.os.AsyncTask$2.call(AsyncTask.java:295) 
>                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
>                                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
>                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
>                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
>                                                                        at java.lang.Thread.run(Thread.java:818) 
>                                                                     Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
>                                                                        at android.os.Handler.<init>(Handler.java:200)
>                                                                        at android.os.Handler.<init>(Handler.java:114)
>                                                                        at android.view.GestureDetector$GestureHandler.<init>(GestureDetector.java:290)
>                                                                        at android.view.GestureDetector.<init>(GestureDetector.java:395)
>                                                                        at android.view.GestureDetector.<init>(GestureDetector.java:376)
>                                                                        at com.jjoe64.graphview.Viewport.<init>(Viewport.java:583)
>                                                                        at com.jjoe64.graphview.GraphView.init(GraphView.java:205)
>                                                                        at com.jjoe64.graphview.GraphView.<init>(GraphView.java:178)
>                                                                        at java.lang.reflect.Constructor.newInstance(Native Method) 
>                                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:631) 
>                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
>                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
>                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
>                                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
>                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
>                                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
>                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
>                                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
>                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
>                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
>                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
>                                                                        at ca.mdt.mdtsmartapp.ui.activity.LinkFEFActivity.setLayoutAndStartReading(LinkFEFActivity.java:838) 
>                                                                        at ca.mdt.mdtsmartapp.ui.activity.LinkFEFActivity.onInstrumentSelected(LinkFEFActivity.java:810) 
>                                                                        at ca.mdt.mdtsmartapp.ui.activity.LinkFEFActivity.isSMARTorLegacy(LinkFEFActivity.java:1031) 
>                                                                        at ca.mdt.mdtsmartapp.ui.activity.LinkFEFActivity.access$4000(LinkFEFActivity.java:108) 
>                                                                        at ca.mdt.mdtsmartapp.ui.activity.LinkFEFActivity$openDevice.doInBackground(LinkFEFActivity.java:2694) 
>                                                                        at ca.mdt.mdtsmartapp.ui.activity.LinkFEFActivity$openDevice.doInBackground(LinkFEFActivity.java:2276) 
>                                                                        at android.os.AsyncTask$2.call(AsyncTask.java:295) 
>                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
>                                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
>                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
>                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
>                                                                        at java.lang.Thread.run(Thread.java:818) 

Compiled library (4.2.1), defined in XML (attempted with both classes GraphView and GraphViewXML), inflated from LayoutInflater.

XML definition is as such:

```
<com.jjoe64.graphview.GraphView
                android:id="@+id/live_graph"
                android:layout_width="match_parent"
                android:layout_height="200dip"
                android:layout_below="@id/readLabel"

                android:visibility="gone"

                android:layout_margin="7dp"
                android:layout_alignParentBottom="true"/>
```

In Android Studio preview, takes up the bottom right portion of the layout, but after inflating it, the app crashes saying I have:

Caused by: android.view.InflateException: Binary XML file line #59: Binary XML file line #59: Error inflating class com.jjoe64.graphview.GraphView

After removing the GraphView, the layout returns to normal.

Did I run out of memory, or?..

**Comment by appsthatmatter** [comment]
please provide complete project so i can reproduce this problem. for now closed
