### ISSUE TITLE
Custom labels are overlapping on each other

### ISSUE THREAD

**Issue by supriya456** [appsthatmatter/GraphView#533]
Hello,

I have to show bar chart but custom labels are overlapping on each other so please help to solve this issue.

Also if have to scroll horizontally so how to do it please help.

Means it will scroll horizontally & how to apply full horizontal scroll at first time.

Please check this screen shot for reference: https://d.pr/V4bI8g

Please share your valuable feedback...

**Comment by Yvtq8K3n** [comment]
Am I to late? Meeeh. here it goes to solve the 1st problem i would recomend u to rotate the x labels.

To solve your 2 next problem:3 i would recomend to define a maxY. Saddly i didnt work whit scroll so i wont be able to help you there;_;

**Comment by appsthatmatter** [comment]
thx
