### ISSUE TITLE
Set min/max axis with date

### ISSUE THREAD

**Issue by myOrax** [appsthatmatter/GraphView#534]
Hello,
I have to show a line graph with date in X axis.
I use the following method for show correctly the dates:
`graph.getGridLabelRenderer().setLabelFormatter(new DateAsXAxisLabelFormatter(getApplicationContext()));`

But I have a problem: I can't set the min and the max value of axis with date because the methods setMinX and setMaxX accept only double value, not date.

How can I solve this problem?

Sorry if my english is not good.

**Comment by Yvtq8K3n** [comment]
I hate alot of problems when combining dates and graphview. My sugestion is for u to do the control yourself whit labelformater . Create a array of strings whit the dates u want and populate the graph.

Exemple:
If your date range is 16/12/1997 to 18/12/2012. 

U gonna have to add points like this: 
new DataPoint(0, value) //case day 0->16/12/1997

new DataPoint(dates.size() , value) //case day 0->18/12/2012. 

Then u have to options set the max and min of labels usualy i set the total of dates i have(dates.size()) and then whit labelformater i replace the values x like this:

graph.getGridLabelRenderer().setLabelFormatter(new DefaultLabelFormatter() {
int counter=0;//adding a counter
    @Override
    public String formatLabel(double value, boolean isValueX) {
        if (isValueX) {
            // show normal x values
            return dates.get(counter++);//set label value and force counter up
        } else {
            // show currency for y values
            return super.formatLabel(value, isValueX);
        }
    }
});

**Comment by appsthatmatter** [comment]
graphview uses the unix time internally, so if you use min/max with a date then use the milliseconds that comes from date.getTime()
