### ISSUE TITLE
Set horizontal and vertical lines at touch and move Y axis

### ISSUE THREAD

**Issue by SaulMaldonado** [appsthatmatter/GraphView#535]
1. Is there a way to show a vertical and a horizontal line at the point tocuhed? see image below
2. Is there a way to draw Y axis over the chart instead of next to it? see image below
![image](https://user-images.githubusercontent.com/32250907/30788690-2b57a4e8-a165-11e7-96e8-581b0250f6e0.png)

**Comment by appsthatmatter** [comment]
since it is not a bug, it's better asked at stackoverflow
