### ISSUE TITLE
Graph is showing unexpected Behavior some times.

### ISSUE THREAD

**Issue by zohaib319** [appsthatmatter/GraphView#539]
A line appears from the 1st quadrant and it meets zero at the origin.
Here is the piece of code

        `graph = (GraphView) view.findViewById(R.id.graph);
        Viewport viewport = graph.getViewport();
        GridLabelRenderer gridlabel1 = graph.getGridLabelRenderer();
        gridlabel1.setHorizontalAxisTitle("Days");
        gridlabel1.setVerticalAxisTitle("Violations");
        final int color = getActivity().getResources().getColor(R.color.colorPrimaryDark);
        gridlabel1.setHorizontalAxisTitleColor(color);
        gridlabel1.setVerticalAxisTitleColor(color);
        viewport.setMinY(0);
        graph.getViewport().setMaxY(30);
        graph.getViewport().setMinX(0);
        graph.getViewport().setMaxX(7);
        graph.getViewport().setYAxisBoundsManual(true);
        graph.getViewport().setXAxisBoundsManual(true);
        final ArrayList<DataPoint> list = new ArrayList<>();
        DataPoint a1 = new DataPoint(0, 0);
        list.add(a1);

        new Timer().scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {

                DataPoint a = new DataPoint(x_axis, y_axis);

                list.add(a);
                DataPoint[] points = new DataPoint[list.size()];

                points = list.toArray(points);

                final LineGraphSeries<DataPoint> series = new LineGraphSeries<>(points);
                Paint paint = new Paint();

                paint.setColor(color);

                series.setThickness(10);
                graph.addSeries(series);

                graph.refreshDrawableState();

            }

        }, 0, 1000);
`
//ends here
![screenshot_2017-10-20-20-08-36-47](https://user-images.githubusercontent.com/22570949/31849153-23c3e398-b657-11e7-8cd4-ccde963bcd52.png)

**Comment by appsthatmatter** [comment]
thx i will check asap

**Comment by appsthatmatter** [comment]
related to #499

**Comment by appsthatmatter** [comment]
@zohaib319 
I did an update, but since I cannot reproduce the problem I ask you to check if it's looking good now, on the devices? I updated the GraphView Demos app in Google Play. So could you please verify?

**Comment by zohaib319** [comment]
I could check it but i am no longer working on the application. So you have
to check it. But when i used it, it was giving unexpected bounds.
Thanks for looking into it.
