### ISSUE TITLE
how to paint horizontal segments 

### ISSUE THREAD

**Issue by jaag12** [appsthatmatter/GraphView#540]
I have tried to paint the horizontal lines but I always connect the segments with vertical lines, how could I do that?
![screenshot_2017-11-03-12-20-12-653_es topdigital clecetecnicos](https://user-images.githubusercontent.com/32569818/32371617-d2090a8e-c091-11e7-85f7-783b344e2662.png)

**Comment by appsthatmatter** [comment]
please ask this on stackoverflow since it is not an issue with the library thx
