### ISSUE TITLE
Label and titles not working

### ISSUE THREAD

**Issue by piotrmajcher94** [appsthatmatter/GraphView#543]
Hi,

I cannot get the labels nor the graph title to work. Here is my code:
`
public class ChartsFragment extends Fragment {
    private static final String TAG = ChartsFragment.class.getName();

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.charts, container, false);

        GraphView graph = (GraphView) view.findViewById(R.id.graph);
        LineGraphSeries<DataPoint> series = new LineGraphSeries<>(new DataPoint[] {
                new DataPoint(0, 1),
                new DataPoint(1, 5),
                new DataPoint(2, 3),
                new DataPoint(3, 2),
                new DataPoint(4, 6)
        });
        graph.setTitle("Title");
        graph.addSeries(series);
        graph.getGridLabelRenderer().setNumHorizontalLabels(5);
        graph.getGridLabelRenderer().setHorizontalLabelsVisible(true);

        return view;
    }
}
`

And a layout:
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="match_parent">  
    <com.jjoe64.graphview.GraphView
        android:layout_width="match_parent"
        android:layout_height="250dip"
        android:id="@+id/graph" />  
</LinearLayout>`

The entire project: https://github.com/piotrmajcher94/PiWindMobile/tree/swibe_tabs

I have tried in many ways and nothing worked.

**Comment by Yvtq8K3n** [comment]
Did u try read the documentation?
Well cause i think it was easy to spot:3

graph.getLegendRenderer().setVisible(true);

Thats your problem, after all u cant show what is invisible:D

**Comment by appsthatmatter** [comment]
thx for your support
