### ISSUE TITLE
Max size

### ISSUE THREAD

**Issue by eleddie** [appsthatmatter/GraphView#544]
Hello,
is there a way to set a max size of i.e. 10 points? 
Or remove the old ones if the size is bigger than 10?

Thanks.

**Comment by Yvtq8K3n** [comment]
There is, but u need to use your brain abit:3
A good tip is to try rotate the labels for them to not overlap.

**Comment by eleddie** [comment]
What do the labels overlapping has to do with the amount of points in the graph?
I'm asking for a solution, not a tip. Am I in high school again?

**Comment by Yvtq8K3n** [comment]
The labels on the x axis will overlap if the amount of labels u put is very high. U have 2 options to solve this problem u can either set a number min and a max to the labels and let the viewport ajust based on the screen size or u can rotate the x labels 90° and hope they dont overlap.

**Comment by eleddie** [comment]
Ok you are totally misunderstanding the issue... 
First of all, I'm not even using labels in any axis. I have a "real time" graph, every time the light sensor detects a change, it creates a new point in the graph. What I want is to have only the last 10 points registered, I don't want to have every point from the start, just the last 10. Is not a labels issue. Is just to delete the first point of the graph if the amount of points is bigger than 10.

**Comment by Yvtq8K3n** [comment]
Ok, i finaly understand your issue, here is the solution. 
Every time the sensor throws the event. Your clear all series from the graph and add the 10 last datapoints.

It could be easly accomplish by doing the following:
```
//Clear Previous Data
    graphQuality.removeAllSeries();

    //Creates an ArrayList
    ArrayList<DataPoint> testList = new ArrayList<>();
    testList.add(new DataPoint(testList.size(), mySensorValue));

    DataPoint[] testArray = new DataPoint[10];
    for(int i=0; i<=10; i++){
        //this will get the last 10 from the list of total points caught
        testArray[i]=testList.get(i+testList.size()-10);
    }

    //Adds the dataPoint array to the graph
    LineGraphSeries<DataPoint> seriesLine = new LineGraphSeries<>(testArray);
    graphQuality.addSeries(seriesLine);

```

**Comment by appsthatmatter** [comment]
there is a parameter for the maximum datapoints in the appendData method that will take care of it

see http://www.android-graphview.org/realtime-chart/

**Comment by dizcza** [comment]
> there is a parameter for the maximum datapoints in the appendData method that will take care of it
> 
> see http://www.android-graphview.org/realtime-chart/

I stumbled upon such a choice of API -> you require the user to pass `maxDataPoints` each time he/she calls the `appendData` method. Wouldn't dedicated functions 
* `series.setMaxDataPoints(100)`
* `series.setAutoScroll(true)`

be a more convenient solution?
