### ISSUE TITLE
Misleading behavior of addSeries

### ISSUE THREAD

**Issue by Meadwild** [appsthatmatter/GraphView#546]
Hello,

I've noticed that when I use  `graph.addSeries(series);` just right after series creation with `series = new LineGraphSeries<>(dataPointsArray);` it works perfectly. But if I just place addSeries inside some additional function and invoke it after it doesn't work properly. DataPoints still will be added, but zooming/scaling processess will lead to their disappearance.

**Comment by appsthatmatter** [comment]
it's working fine with the example code. please provide isolated code to debug it
