### ISSUE TITLE
Line graph with breaks

### ISSUE THREAD

**Issue by romariomkk** [appsthatmatter/GraphView#547]
My data has no null values and seems to be perfect. The graph must obtain a step-like shape. Yet, all the vertical lines are missing. Attaching screenshot of data and graph. How to resolve that?
![photo_2017-12-10_17-43-43](https://user-images.githubusercontent.com/17495334/33806493-b2af4b46-ddd1-11e7-85e7-467b6fb0df30.jpg)
![image](https://user-images.githubusercontent.com/17495334/33806502-cdeaa806-ddd1-11e7-8df4-a7bf89e8c1d1.png)
Second one does not include all the data.

**Comment by appsthatmatter** [comment]
i need a project (java files) to debug it
