### ISSUE TITLE
setLegendRender

### ISSUE THREAD

**Issue by Yvtq8K3n** [appsthatmatter/GraphView#549]
Unable to create my own costum legend. Some times i have a extra serie which im unable to remove from the legend because how it is implemented. Also a way to create a costum legend would be nice.

Sugestion:
Maybe create a method that facilitate the process and can be easly @Overriten.

it could be something like drawCostum() that recieves an array, linkedlist, arraylist of strings and an array os colours or something like that

**Comment by appsthatmatter** [comment]
should be possible by extending the LegendRenderer class
