### ISSUE TITLE
How to hide x and y labels?

### ISSUE THREAD

**Issue by ToysoftInc** [appsthatmatter/GraphView#566]
I can set custom labels but is there a way to hide both the X and Y labels?

**Comment by robachmann** [comment]
I believe you're looking for something like this:
```
mGraphView.getGridLabelRenderer().setVerticalLabelsVisible(false);
mGraphView.getGridLabelRenderer().setHorizontalLabelsVisible(false);
```

**Comment by ToysoftInc** [comment]
That works. thanks!!!
I misunderstood the api.  I thought those two apis are for custom labels inside the graph.
