### ISSUE TITLE
Time Line charts

### ISSUE THREAD

**Issue by Hitesh12345678** [appsthatmatter/GraphView#567]
There is no such option provided for Time line charts in this Charts like : 
[google time line charts](https://developers.google.com/chart/interactive/docs/gallery/timeline)

**Comment by appsthatmatter** [comment]
no currently not

**Comment by Hitesh12345678** [comment]
then please provide us

**Comment by appsthatmatter** [comment]
it's an open source project, so anyone is invited to contribute
