### ISSUE TITLE
How to add margin between graph and secondscale vertical labels?

### ISSUE THREAD

**Issue by personaljesusua** [appsthatmatter/GraphView#568]
Is this possible to add margin between vertical labels of SecondScale and graph (or series)?

here https://i.imgur.com/09ktOPl.jpg

**Comment by appsthatmatter** [comment]
i think you can define the width. take a deep look into the api. or add a space char to the labels.
no bug, so i have to close

**Comment by cau-no** [comment]
The GridLabelRenderer.setLabelSpace() and .setLabelVerticalWidth() work only on the first Y-Scale, not the second. SecondScale does not have such methods. Adding an extra Formatter is not feasible.

The spaces should default to the same value on both sides.
